Title: Review Course Structure, Objectives, and Requirements
TOC: yes
Author: Thomas J. Kennedy


While the syllabus is a bit of a dry read (as all syllabi tend to be)... a few
sections are particularly important during the first week of class.


# Course Learning Objectives

Make sure that you have reviewed the syllabus, specifically section 2.4
(Objectives).

{{Objectives}}


# Textbooks and Supplemental Materials

Make sure that you have reviewed the syllabus, specifically section 2.1
(Textbooks)...


{{Textbooks}}


and section 2.2 (Supplemental Materials)...


{{Supplemental Materials}}


# Technology Requirements

Make sure that you have reviewed the syllabus, specifically section 2.3
(Technology Requirements) and all subsections therein.


## Computer Accounts 

Make sure that you have reviewed the syllabus, specifically section 2.3.1
(Computer Accounts).

{{Computer Accounts}}


## Compilers & Interpreters

Make sure that you have reviewed the syllabus, specifically section 2.3.2
(Compilers and Interpreters).

{{Compilers and Interpreters}}


# Vendor Accesibility Statements

  - Canvas: [What are Canvas Accessibility Standards?](https://community.canvaslms.com/t5/Canvas-Basics-Guide/What-are-the-Canvas-accessibility-standards/ta-p/1564)
  - Zoom: [Zoom is for Everyone](https://www.zoom.com/en/accessibility/)
  - Microsoft 365: [An Inclusive, Accessible Microsoft 365](https://www.microsoft.com/en-us/accessibility/microsoft-365?activetab=pivot_1:primaryr2)
  - GitHub: [GitHub Accessibility](https://accessibility.github.com/)


